scrape_configs:
  - job_name: "admin-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["http://192.168.0.105:8082"]

  - job_name: "configuration-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["http://192.168.0.105:8081"]

  - job_name: "translation-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["http://192.168.0.105:8083"]