services:
  postgres:
    image: postgres:latest
    container_name: magic-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres/pgdata:/var/lib/postgresql/data
    networks:
      - salas-project-bridge


  consul:
    image: consul:1.15.4
    container_name: consul-server
    ports:
      - "8500:8500"     # Web UI и HTTP API
      - "8600:8600/udp" # DNS (опционально)
    volumes:
      - ./tmp/consul/salas_project_consul_data:/consul/data
      - ./tmp/consul/config:/consul/config
    command:
      - agent
      - -server
      - -ui
      - -client=0.0.0.0
      - -data-dir=/consul/data
      - -bootstrap-expect=1
      - -config-file=/consul/config/agent.json
    networks:
      - salas-project-bridge

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.119.0
    container_name: victoriametrics
    ports:
      - "8428:8428"  # веб-интерфейс и HTTP API
    volumes:
      - ./config/victoriametrics:/config
      - ./tmp/victoriametrics-data:/victoria-metrics-data
    command:
      - --retentionPeriod=30d  # необязательно, настройка хранения
      - -promscrape.config=/config/promscrape.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.4
    container_name: grafana-server
    ports:
      - '3000:3000'
    volumes:
      - ./tmt/grafana:/var/lib/grafana


networks:
  salas-project-bridge:
    driver: bridge
