spring:
  application:
    name: configuration-service

  config:
    import: 'consul:'
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        instance-id: configuration-service
        acl-token: ad17e755-1a49-c18e-b453-23332419b68b
      config:
        acl-token: ad17e755-1a49-c18e-b453-23332419b68b

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: configuration-service