spring:
  application:
    name: configuration-service

  config:
    import: 'consul:'
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        instance-id: configuration-service

server:
  port: 8081
