spring:
  application:
    name: admin-service
  config:
    import: 'consul:'

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        instance-id: admin-service
        acl-token: 35472bac-d144-f832-2cff-6aa1dc16549b
      config:
        format: yaml
        data-key: data #default data
        acl-token: 35472bac-d144-f832-2cff-6aa1dc16549b

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true
