spring:
  application:
    name: admin-service
  config:
    import: 'consul:'

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        instance-id: admin-service
        acl-token: 35472bac-d144-f832-2cff-6aa1dc16549b
      config:
        format: yaml
        data-key: data #default data
        acl-token: 35472bac-d144-f832-2cff-6aa1dc16549b
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
          - info
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true

