spring:
  application:
    name: admin-service

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        instance-id: admin-service

server:
  port: 8082
