spring:
  application:
    name: admin-service
  config:
    import: 'consul:'

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        instance-id: admin-service
      config:
        format: yaml
        data-key: data #default data