spring:
  application:
    name: product-service
server:
  port: 0

topics:
  topics-name:
    topic-product: salas-odesa-topic
    topic-withdraw: withdrew-event-topic
    topic-deposit: deposit-event-topic