spring:
  application:
    name: product-service
server:
  port: 0

topics:
  topics-name:
    topic-product: salas-odesa-topic
    topic-withdraw: withdraw-event-topic
    topic-deposit: deposit-event-topic

logging:
  level:
    org:
      springframework:
        transaction: trace
        kafka:
          transaction: trace